// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omxtrdmtdrdovculcywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9teHRyZG10ZHJkb3ZjdWxjeXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjc0OTYsImV4cCI6MjA1OTc0MzQ5Nn0.X3d2EfZyqAbJofb98ypnJt7tH7jKx1PdG58DRgZ9qQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);